### ISSUE TITLE
Some requestions

### ISSUE THREAD

**Issue by code-Sky-JT** [haoopeng/diffusion_speed#1]
Hello, thank you very much for your research on this research topic. I've been reading your paper recently. In the process of reproducing the results of the paper, I have some questions. First of all, I want to ask you, such as in LFR_ hpc.py File, will generate 50 documents, and then how to analyze these 50 documents, and then generate the final data for drawing, SBM, LFR and twitter networks have this problem. Secondly, because of the limitation of my computer configuration, it takes me seven or eight hours to run a cycle in a code. If it's convenient, I hope you can send the following four documents to my mailbox.
e-mail address: Sky-JT@outlook.com
1、phase_ simu_ twitter_ thsh_ 0.3_ F_ 0.01.pickle
2、partition_ twitter.pickle
3、phase_ simu_ nodes_ 100k_ Z_ 10_ thsh_ 0.3_ F_ 0.01.pickle(For FLR network)
4、phase_ simu_ nodes_ 100k_ Z_ 10_ thsh_ 0.35_ F_ 0.01.pickle(For SBM network)
Finally, thank you again for your help!

**Comment by haoopeng** [comment]
Hi, Thanks for reaching out! I have reorganized the code and updated the documentation. Once you generated the 51 documents on a computer server, you can go back to the `.ipynb` file to combine then into a single pickle file (the code is commented).
